active_personality_id: 0
audio_auto_send_input: true
audio_in_language: en-US
audio_out_voice: English United States
audio_pitch: 1
audio_silenceTimer: 5000
auto_save: false
auto_show_browser: true
auto_speak: true
auto_update: true
binding_name: gptq
config: local_config
ctx_size: 8192
data_vectorization_activate: true
data_vectorization_build_keys_words: false
data_vectorization_chunk_size: 512
data_vectorization_method: ftidf_vectorizer
data_vectorization_nb_chunks: 2
data_vectorization_overlap_size: 128
data_vectorization_save_db: false
data_visualization_method: PCA
db_path: /home/mdupont/ggml/database/database.db
debug: true
discussion_prompt_separator: '!@>'
enable_gpu: true
host: 0.0.0.0
model_name: llama2-7b-chat-codeCherryPop-qLoRA-GPTQ
n_predict: 1056
n_threads: 8
override_personality_model_parameters: true
personalities:
- generic/lollms
port: 9600
repeat_last_n: 40
repeat_penalty: 1.2
seed: -1
temperature: 2.3
top_k: 50
top_p: 0.95
use_files: true
use_user_informations_in_discussion: false
use_user_name_in_discussions: false
user_avatar: default_user.svg
user_description: ''
user_name: user
version: 23
